erDiagram
CREDIT_SOLICITATION {
protocol
status
public_user
credit_line
proposal
agent
backoffice
created_at
updated_at
}

SOLICITATION_PARTICIPANT {
solicitation
user
created_at
updated_at
}

SOLICITATION_HISTORY {
solicitation
action
timestamp
created_at
updated_at
}

SOLICITATION_TASK {
solicitation
description
stage
sequence
is_completed
due_date
created_at
updated_at
}

SOLICITATION_DOCUMENTS {
document_type
registration_number
issuing_body
date_of_issue
photo
description
solicitation
created_at
updated_at
}

SOLICITATION_ENTERPRISE_PHOTOS {
solicitation
photo
description
created_at
updated_at
}

SOLICITATION_REFERENCES {
description
degree_of_kinship
phone_one
phone_two
solicitation
created_at
updated_at
}

SOLICITATION_PROPERTY {
property_type
property_conditions
has_movable_property
physical_structure_of_the_business
is_own_property
solicitation
created_at
updated_at
}

SOLICITATION_DATA {
line_of_credit
credit_purpose
solicitation_text
grace_period
amortization_term
full_term
interest_rate
rate_analysis
claimed_amount
duration
payment_term
shopping_frequency
solicitation
created_at
updated_at
}

CREDIT_SOLICITATION ||--o{ SOLICITATION_PARTICIPANT : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_HISTORY : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_TASK : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_DOCUMENTS : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_ENTERPRISE_PHOTOS : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_REFERENCES : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_PROPERTY : possui
CREDIT_SOLICITATION ||--o{ SOLICITATION_DATA : possui 
